In [1]:
import numpy as np
np.__version__

'1.20.2'

In [2]:
t = np.zeros(10)
t

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
t.shape = (2,5)
t

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [4]:
t = np.ones(10)
t

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
t = np.empty(10)
t

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
t = np.linspace(1,10,5)
t

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [8]:
?t #documenter sur 't'

Object `t #documenter sur 't'` not found.


In [9]:
myList = [[3,4,5,6,7,9,1,0,1]]
nt = np.array(myList)
nt

array([[3, 4, 5, 6, 7, 9, 1, 0, 1]])

In [10]:
nt.shape = (3,3)
nt

array([[3, 4, 5],
       [6, 7, 9],
       [1, 0, 1]])

In [11]:
type(nt)

numpy.ndarray

In [12]:
r = np.random.randint(100,size=10)
r

array([54, 48, 13, 84, 55, 91, 84, 86, 66, 12])

In [13]:
r%2==0

array([ True,  True, False,  True, False, False,  True,  True,  True,
        True])

In [14]:
nt[nt>1]

array([3, 4, 5, 6, 7, 9])

In [15]:
nt=np.where(nt==0,1,0)
nt

array([[0, 0, 0],
       [0, 0, 0],
       [0, 1, 0]])

In [16]:
nt*2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 2, 0]])

In [17]:
nt-1

array([[-1, -1, -1],
       [-1, -1, -1],
       [-1,  0, -1]])

In [18]:
nt = nt+np.array(myList).reshape(3,3)
nt

array([[3, 4, 5],
       [6, 7, 9],
       [1, 1, 1]])

In [19]:
nt.ndim  #le nbr de demension

2

In [20]:
tip = np.array((1,2,3))
len(tip)

3

In [21]:
tip

array([1, 2, 3])

In [22]:
tip = np.array(tip, ndmin=3)
tip

array([[[1, 2, 3]]])

In [23]:
tip.dtype

dtype('int64')

In [24]:
t = np.full((3,3),True,dtype=bool)
t

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [25]:
t = np.full_like(myList,-1,dtype="f")
t

array([[-1., -1., -1., -1., -1., -1., -1., -1., -1.]], dtype=float32)

In [26]:
t1=np.arange(0,20,2).reshape(2,5)
t1.reshape(-1)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [27]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
np.eye(2, dtype='i')

array([[1, 0],
       [0, 1]], dtype=int32)

In [29]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [30]:
np.eye(3,4,1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [31]:
t1 = np.fromfunction(lambda i,j: i*j, (3,2))

In [32]:
for e in np.nditer(t1):
    print(e)

0.0
0.0
0.0
1.0
0.0
2.0


In [33]:
np.arange(12,29,2)[::-1]

array([28, 26, 24, 22, 20, 18, 16, 14, 12])

In [34]:
def f(n):
    return np.eye(n,n)*n + np.eye(n,n,1) + np.eye(n,n,-1)

In [35]:
f(4)

array([[4., 1., 0., 0.],
       [1., 4., 1., 0.],
       [0., 1., 4., 1.],
       [0., 0., 1., 4.]])

In [36]:
def f2(n):
    return sum(np.arange(1,n+1))

In [37]:
f2(9)

45

In [38]:
np.linspace(1,36, dtype='i')*0

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0], dtype=int32)

In [39]:
np.random.seed(1)
prix=np.random.randint(100000,300000,[10,1])
surface=np.random.randint(50,120,[10,1])
qualite=np.random.randint(1,4,[10,1])
garage=np.random.randint(0,2,[10,1],dtype=bool)
appartements=np.hstack([prix,surface,qualite,garage])
appartements

array([[228037,     56,      1,      0],
       [105192,     75,      2,      1],
       [150057,    100,      2,      1],
       [209259,     70,      3,      0],
       [173349,     68,      1,      1],
       [217583,     61,      3,      0],
       [121440,     78,      2,      0],
       [251681,     79,      2,      0],
       [280172,     64,      2,      0],
       [238823,    100,      2,      1]])

1. Calculer le maximum par rapport à chaque entité (prix, surface et qualité)
2. Afficher l'indice de la surface minimale
3. Affecter à l'appartemen ayant la surface minimale le prix minimum.

In [40]:
appartements.max(axis=0)

array([280172,    100,      3,      1])

In [41]:
appartements.argmin(axis=0)[0]

1

In [42]:
nt

array([[3, 4, 5],
       [6, 7, 9],
       [1, 1, 1]])

In [43]:
np.fill_diagonal(nt,1)
nt

array([[1, 4, 5],
       [6, 1, 9],
       [1, 1, 1]])

In [64]:
np.array_split(nt,3)

[array([[1, 4, 5]]), array([[6, 1, 9]]), array([[1, 1, 1]])]

In [68]:
np.sort(nt)

array([[1, 4, 5],
       [1, 6, 9],
       [1, 1, 1]])