## Exercices (partie II) : Mathématique avec Numpy

In [2]:
import numpy as np

Q1. Trouver la valeur maximale et minimale d'un tableau donné.

In [6]:
A=np.random.randint(-5,5,(3,3))
print(A)
print('minimum',A.min() )
print('maximum',A.max() )

[[-1 -4  2]
 [-3  4  3]
 [ 2 -3  0]]
minimum -4
maximum 4


Q2. Obtenir la valeur minimale et maximale d'un tableau donné le long du deuxième axe.

In [9]:
A.min(axis=1)

array([-4, -3, -3])

In [10]:
A.max(axis=1)

array([2, 4, 2])

Q3. Calculer la différence entre les valeurs maximale et minimale d'un tableau donné le long du deuxième axe.

In [11]:
A.max(axis=1)-A.min(axis=1)

array([6, 7, 5])

Q5. Calculer la moyenne, l'écart type et la variance d'un tableau donné le long du deuxième axe.

In [23]:
print('moyenne', B.mean(axis=1))
print('ecart type', B.std(axis=1))
print('variance', B.var(axis=1))

moyenne [7. 2.]
ecart type [2.44948974 0.81649658]
variance [6.         0.66666667]


Q6. Calculer la matrice de covariance de deux tableaux donnés.

In [29]:
x =np.array([-2.1, -1,  4.3])
y =np.array( [3,  1.1,  0.12])
np.cov(x,y)

array([[11.71      , -4.286     ],
       [-4.286     ,  2.14413333]])

Q7. Calculer les coefficients de corrélation deux tableaux 1D donnés.

In [33]:
np.corrcoef(x,y)

array([[ 1.        , -0.85535781],
       [-0.85535781,  1.        ]])

Q8. Multiplier une matrice 5x3 par une matrice 3x2.

In [36]:
E=np.random.randn(5,3)
F=np.random.randn(3,2)
E@F

array([[ 1.02997988, -2.04993374],
       [ 0.38400743, -0.92187361],
       [ 0.79787672, -2.56984293],
       [ 0.87568337, -2.52695916],
       [ 0.92455849, -3.43538393]])

In [37]:
# ou bien
E.dot(F)

array([[ 1.02997988, -2.04993374],
       [ 0.38400743, -0.92187361],
       [ 0.79787672, -2.56984293],
       [ 0.87568337, -2.52695916],
       [ 0.92455849, -3.43538393]])

Q9. Calculer le produit cumulatif des éléments le long d'un axe d'un tableau 3x3 donné.

In [38]:
print(A)
A.cumprod(axis=0)

[[-1 -4  2]
 [-3  4  3]
 [ 2 -3  0]]


array([[ -1,  -4,   2],
       [  3, -16,   6],
       [  6,  48,   0]], dtype=int32)

Q10. Calculer $e^x$, par élément d'un tableau $x$ donné.

In [40]:
x=np.linspace(0,10,5)
print(x)
np.exp(x)

[ 0.   2.5  5.   7.5 10. ]


array([1.00000000e+00, 1.21824940e+01, 1.48413159e+02, 1.80804241e+03,
       2.20264658e+04])

Q12. Calculer le déterminant d'un tableau carré donné.

In [44]:
np.linalg.det(A)

-31.000000000000014

Q13. Calculer les valeurs propres et les vecteurs propres d'un tableau carré donné.

In [48]:
val,vect=np.linalg.eig(A)
print("les valeurs propres sont :\n",val)
print("les vecteurs propres sont :\n",vect)

les valeurs propres sont :
 [-3.26816884  3.71464543  2.55352341]
les vecteurs propres sont :
 [[-0.890375   -0.62662351  0.64249677]
 [-0.42963021  0.40595816 -0.20106162]
 [ 0.15049998 -0.66523752  0.73944041]]


Q14. Calculer la somme de l'élément diagonal d'un tableau donné.

In [53]:
A.diagonal().sum()

3

In [54]:
# ou bien
np.sum(np.diag(A))

3

Q15. trouver la valeur la plus fréquente dans un tableau.

In [64]:
valeurs,counts=np.unique(A,return_counts=True)
valeurs[counts.argmax()]

-3

Q16. Résoudre le système suivant :

$$\left(
\begin{array}{ccc}
1&-2&1\\
2&0&5\\
-3&1&6
\end{array}
\right) \left(
\begin{array}{c}
x\\
y\\
z
\end{array}
\right)=\left(
\begin{array}{c}
-1\\
1\\
3
\end{array}
\right)$$

In [74]:
C=np.array([[1,-2,1],
           [2,0,5],
           [-3,1,6]])
b=np.array([[-1],[1],[3]])
print('le determinant est ',np.linalg.det(C)) # tres important pour savoir si la matrice est inverssible
sol=np.linalg.inv(C)@b
print('la solution est :\n',sol)

le determinant est  51.0
la solution est :
 [[-0.23529412]
 [ 0.52941176]
 [ 0.29411765]]
