# Programmation en Python
### DUT IDSD 1
#### 2020/2021

## Chapitre 6 : Module Numpy

* **Numpy** est la librairie qui offre la pièce fondamentale pour faire du calcul scientifique avec Python. 


* Elle est majoritairement écrite en C et Python. Quelques portions sont également écrites en C++ et Fortran.


* Elle étend les capacités de Python pour travailler sur des tableaux et matrices à n dimensions de façon bien plus optimisée et offre des fonctions mathématiques de haut niveau sur ces objets.

## I. Description de Numpy

### Importation
Par convention, la communauté importe Numpy de la façon suivante. 

In [1]:
import numpy as np

Pour voir la liste des fonctionalités proposée par ce module, il suffit de tapez np. suivez d'une tabulation pour que une liste des méthodes s'afiche. Par exemple pour le savoir le path de Numpy je tape :

<img src='np.png' />

In [2]:
np.__path__

['/home/abdelghafour/.local/lib/python3.8/site-packages/numpy']

### Création d'objets ndarray
L'objet **ndarray** pour N-dimensional array est l'élément central de la librairie Numpy.

Tout ce qui est décrit ci-dessous a pour vocation de travailler sur ces objets, de la création, aux opérations en passant par leurs attributs et les manipulations possibles.

### L'objet : np.array( )
Il peut être créé de plusieurs façons. La première est en utilisant **np.array():**

In [3]:
Variable=np.array(object, dtype=None)

- **object** : un array ou objet exposant une interface de type array (listes,…).

- **dtype** : est le type choisi pour les données qui y seront stockées.


In [4]:
a=np.array([1,2,3],dtype='uint32')
print(a)

[1 2 3]


Voici les principaux types disponibles :
* np.bool : Booléen (True|False)
* np.int8 : Entier (-128 à 127)
* np.int16 : Entier (-2¹⁵ à 2¹⁵-1)
* np.int32 : Entier (-2³¹ à 2³¹-1)
* np.int64 : Entier (-2⁶³ à 2⁶³-1)
* np.uint8 : Entier (0 à 255)
* np.uint16 : Entier (0 à 2¹⁶-1)
* np.uint32 : Entier (0 à 2³²-1)
* np.uint64 : Entier (0 à 2⁶⁴-1)
* np.float16 : Flottant (demi-précision flottant)
* np.float32 : Flottant (simple-précision flottant)
* np.float64 : Flottant (double-précision flottant)
* np.complex64 : Complexe

**Exemples :**

In [5]:
a = np.array([6.1, 7.2, 8.3])
a

array([6.1, 7.2, 8.3])

In [6]:
type(a)

numpy.ndarray

In [7]:
a.dtype 

dtype('float64')

----

In [13]:
b = np.array([1, 2, 3], dtype=np.uint64)
b

array([1, 2, 3], dtype=uint64)

In [9]:
b.dtype

dtype('uint64')

In [10]:
np.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

### Création d'un intervalle avec np.arange( )

In [11]:
np.arange(start, stop, step, dtype=None)

NameError: name 'start' is not defined

Elle retourne un ndarray avec des valeurs réparties sur l'intervalle demandé avec un pas (step).
* start : valeur de début (facultatif)
* stop : valeur de fin
* step : saut entre chaque valeur (par défaut 1)
* dtype : type choisi

De la même façon que pour la fonction range() de Python, la valeur stop ne fait pas partie des valeurs retournées.

**Exemples :**

In [14]:
np.arange(1, 5)

array([1, 2, 3, 4])

In [15]:
np.arange(5.0)

array([0., 1., 2., 3., 4.])

---

In [16]:
np.arange(1, 3, 0.5)

array([1. , 1.5, 2. , 2.5])

In [17]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Création d'un intervalle avec np.linspace( )

In [ ]:
Syntaxe : 
    np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)

Elle retourne un ndarray avec des valeurs réparties sur l'intervalle demandé.

* num : nombre de valeurs souhaitées (50 par défaut)

* endpoint : inclure ou pas la valeur stop (True par défaut)

* retstep : si True, retourne un tuple

**Exemples :**

In [18]:
np.linspace(1, 10, 3)

array([ 1. ,  5.5, 10. ])

On peut calculer le pas par la formule $\dfrac{(b-a)}{(N-1)}$ avec $a=start$, $b=stop$ et $N=nombre$

In [ ]:
np.linspace(1, 10, 3, endpoint=False)

Ici, on peut calculer le pas par la formule $\dfrac{(b-a)}{(N)}$ avec $a=start$, $b=stop$ et $N=nombre$

In [19]:
np.linspace(1, 2, 5, retstep=True)

(array([1.  , 1.25, 1.5 , 1.75, 2.  ]), 0.25)

### Création de ndarrays avec np.zeros(), np.ones() et np.full()

Retourne un ndarray de géométrie demandée, rempli avec des 0 ou 1 ou la valeur demandée.

In [ ]:
Syntaxes : 
    np.zeros(shape, dtype=float)
    np.ones(shape, dtype=float)
    np.full(shape, fill_value, dtype=float)

* shape : géométrie désirée
* fill_value : valeur d'initialisation pour chaque élément du ndarray.

**Exemples :**

In [20]:
np.zeros((5,1), dtype=int)

array([[0],
       [0],
       [0],
       [0],
       [0]])

In [21]:
np.zeros((2, 3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [22]:
np.full(5, -1, dtype=int)

array([-1, -1, -1, -1, -1])

In [24]:
np.full((2, 3), 5, dtype=int)

array([[5, 5, 5],
       [5, 5, 5]])

### Création de ndarrays avec np.zeros_like( ), np.ones_like( ) et np.full_like( )

Retourne un ndarray de géométrie identique au ndarray passé en paramètre, rempli avec des 0 ou 1 ou la valeur demandée.

In [ ]:
Syntaxe :
    np.zeros_like(a, dtype=float)
    np.ones_like(a, dtype=float)
    np.full_like(a, fill_value, dtype=float)

* a : objet ndarray dont on récupère la géométrie
* fill_value : valeur d'initialisation pour chaque élément du ndarray.

**Exemples :**

In [25]:
a = np.full((3, 7),3,dtype=int)
a

array([[3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3]])

In [26]:
np.full_like(a, 5)

array([[5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5]])

In [27]:
np.ones_like(a)

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]])

### Génération de ndarray à valeurs aléatoires avec np.random

Retourne un ndarray avec la géométrie définie par les arguments contenant des valeurs aléatoires de distribution uniforme dans l'interval $[0, 1)$.


In [ ]:
Syntaxe : 
    np.random.rand(d0, d1, ..., dn)

* d0, d1, ..., dn : les dimensions pour chaque axe.

**Exemple :**

In [28]:
np.random.rand(2, 3)

array([[0.18894573, 0.60548609, 0.83599777],
       [0.71841428, 0.54614159, 0.94432751]])

Pour avoir des valeurs centrées en 0 en utilise la fonction **np.random.randn**

In [29]:
np.random.randn(2, 3)

array([[ 0.5424353 , -2.06534491, -0.07816708],
       [-0.34001547, -0.69455623,  0.7865342 ]])

### Génération de ndarray à valeurs aléatoires avec np.random

Retourne un ndarray avec la géométrie définie par size contenant des valeurs entières aléatoires.

In [ ]:
Syntaxe :
    np.random.randint(low, high=None, size=None)

* low : valeur inférieure
* high : valeur supérieure (non-inclue).
* size : entier donnant la dimension ou tuple décrivant la géométrie du ndarray retourné. Si il n'est pas donné, retournera un scalaire.

**Exemples :**

In [30]:
np.random.randint(1, 7, 10)

array([2, 3, 6, 4, 2, 1, 2, 4, 4, 4])

In [31]:
np.random.randint(1, 300, 5).min()

89

In [32]:
np.random.randint(1, 300, 10).max()

277

In [33]:
np.random.randint(1, 20, (2,4))

array([[ 4,  3, 14, 15],
       [ 7,  9,  8,  1]])

### Génération de ndarray à valeurs aléatoires avec np.random

In [ ]:
Syntaxe :
    np.random.random(size=None)

Retourne un ndarray avec la géométrie définie par size contenant des valeurs aléatoires (0 <= x < 1).

In [34]:
np.random.shuffle(x)

NameError: name 'x' is not defined

Modifie un ndarray en mélangeant ses éléments selon son premier axe.

**Exemples :**

In [35]:
a=np.random.random((3,2))
a

array([[0.08835202, 0.29551587],
       [0.14866231, 0.11615703],
       [0.98730268, 0.45205093]])

In [37]:
np.random.shuffle(a)
a

array([[0.08835202, 0.29551587],
       [0.98730268, 0.45205093],
       [0.14866231, 0.11615703]])

In [40]:
np.random.choice([4,5,8,-5,1,2,20], size=None)

1

Retourne un ndarray d'éléments choisis au hasard d'un 1-D array

* a : 1-D array duquel seront pris les éléments choisis au hasard. Si c'est un entier, alors il est généré comme si c'était np.arange(a)

* size : géométrie du ndarray désiré

**Exemples :**

In [41]:
np.random.choice(10, (2, 3))

array([[1, 3, 3],
       [2, 9, 5]])

In [42]:
np.random.choice(['a', 'b', 'c'], (2, 3))

array([['a', 'c', 'a'],
       ['c', 'a', 'b']], dtype='<U1')

## II. Manipulation et attributs d'objets ndarray

### Type de données (dtype)

In [43]:
a = np.array([1, 2, 3, 4])
a.dtype

dtype('int64')

### Géométrie de l’objet (shape)

In [44]:
b = np.linspace(1, 6, 6)
b.shape

(6,)

### Modifier la géométrie (reshape)

In [45]:
b

array([1., 2., 3., 4., 5., 6.])

In [46]:
b.reshape((2,3))

array([[1., 2., 3.],
       [4., 5., 6.]])

In [47]:
b

array([1., 2., 3., 4., 5., 6.])

Il est possible de donner -1 sur une dimension, dans ce cas, la valeur est calculée en fonction de la taille de l'objet.

In [48]:
b.reshape((2,-1))

array([[1., 2., 3.],
       [4., 5., 6.]])

### Transposer de l’objet

In [49]:
c=np.zeros((3,2))
c

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [50]:
c.T

array([[0., 0., 0.],
       [0., 0., 0.]])

In [51]:
c

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

On peut aussi utiliser la méthode shape comme suit :

In [52]:
b.shape=(6,1)
b

array([[1.],
       [2.],
       [3.],
       [4.],
       [5.],
       [6.]])

### Empilez les tableaux

#### horizontalement.

**numpy.hstack ([d0,d1,...,dn])**<br>
Empilez les tableaux en séquence horizontalement (colonne par colonne).
Cela équivaut à une concaténation le long du deuxième axe, sauf pour les tableaux 1D où elle concatène le long du premier axe. 

In [56]:
a = np.arange(10).reshape(2,-1)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [57]:
b = np.repeat(1, 10).reshape(2,-1)
b

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [60]:
c = np.repeat(-7, 10).reshape(2,-1)
c

array([[-7, -7, -7, -7, -7],
       [-7, -7, -7, -7, -7]])

In [59]:
np.hstack([a, b, c])

array([[ 0,  1,  2,  3,  4,  1,  1,  1,  1,  1, -7, -7, -7, -7, -7],
       [ 5,  6,  7,  8,  9,  1,  1,  1,  1,  1, -7, -7, -7, -7, -7]])

#### Verticalement

de la même manière avec la commande **np.vstack([d0, d1, ..., dn])**

In [61]:
np.vstack([a,b,c])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [ 1,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1],
       [-7, -7, -7, -7, -7],
       [-7, -7, -7, -7, -7]])

### Intersection de deux tableaux

**numpy.intersect1d (ar1, ar2, assume_unique = False, return_indices = False)**<br>

Trouvez l'intersection de deux tableaux. Renvoie les valeurs triées et uniques qui se trouvent dans les deux tableaux d'entrée.

In [62]:
np.intersect1d([1, 3, 4, 3], [3, 1, 2, 1])

array([1, 3])

### Différence entre deux tableaux

**numpy.setdiff1d (ar1, ar2, assume_unique = False)**<br>
Trouvez la différence définie de deux tableaux.

In [63]:
a = np.array([1, 2, 3, 2, 4, 1])
b = np.array([3, 4, 5, 6])
np.setdiff1d(a, b)

array([1, 2])

### Rechercher des éléments

**numpy.where (condition)**<br>
Retourne les indices des éléments satisfaisant la condition.

In [70]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
np.where(a < 5)

(array([0, 1, 2, 3, 4]),)

In [72]:
t=np.linspace(3,8,6)
t

array([3., 4., 5., 6., 7., 8.])

In [75]:
np.where(t < 5)

(array([0, 1]),)

**numpy.where (condition,ndarray,val_si_faux)**<br>
Retourne un tableau de même taille que le tableau ndarray contenant les élémenets satisfaisant la condition et la valeur *val_si_faux* à la place des autres éléments.

In [76]:
np.where(a < 5, a, 10*a)

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

In [77]:
np.where(a >=6, a, -1)

array([-1, -1, -1, -1, -1, -1,  6,  7,  8,  9])

### Indexing et Slicing

- Il est possible d'accéder à un élément ou un ensemble d'éléments à l'intérieur d'un ndarray avec l'indexing et le slicing. Cela se fait en donnant le/les index entre [].

- Lorsque la valeur est positive, on indexe depuis le début du ndarray, lorsqu'elle est négative, depuis la fin.

- Pour un ndarray à multiple dimensions, on sépare chaque index (ou slice) avec une ,

**Exemples :**

In [78]:
a = np.arange(10).reshape((2, -1))
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [79]:
a[1] # ou a[1, :]

array([5, 6, 7, 8, 9])

In [80]:
a[:, 1]

array([1, 6])

### Indexing avec un tableau
Il est possible de donner un tableau d'index. Cela retournera un ndarray de la même dimension avec les valeurs correspondantes.

In [81]:
a = np.arange(7)[::-1]
a 

array([6, 5, 4, 3, 2, 1, 0])

In [82]:
i = np.array([1, 5, 2, 2, 6])
a[i]

array([5, 1, 4, 4, 0])

### Indexing avec un masque
Il est possible de filtrer un ndarray à l'aide d'un masque booléen. Pour cela, il est nécessaire que le masque soit de la même dimension que l'objet filtré.

**Exemples :**

In [83]:
a = np.arange(8, 13)[::-1]
a 

array([12, 11, 10,  9,  8])

In [84]:
m = a>10
m 

array([ True,  True, False, False, False])

In [85]:
a[m]

array([12, 11])

In [86]:
a[a>10]

array([12, 11])

### Affectation indexée
Pour chaque syntaxe où l'on obtient une vue à l'aide d'index ou d'un slicing, il est possible de l'utiliser dans une affectation, ce qui viendra écraser les valeurs correspondantes.

**Exemples :**

In [87]:
a = np.arange(10)
a[3:5] = 0
a

array([0, 1, 2, 0, 0, 5, 6, 7, 8, 9])

In [88]:
a[4:7] = np.arange(3)[::-1]
a

array([0, 1, 2, 0, 2, 1, 0, 7, 8, 9])

In [89]:
a[np.array([7, 5, 9])] -= 1
a 

array([0, 1, 2, 0, 2, 0, 0, 6, 8, 8])

In [90]:
a[a>5] = 0
a

array([0, 1, 2, 0, 2, 0, 0, 0, 0, 0])